name: Build LEDE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 3 * *'
permissions: 
  contents: write
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_NAME: lede
  WORKDIR: /mnt/lede
  CCACHE_DIR: /mnt/ccache_lede
  CCACHE_MAXSIZE: 10G

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Prepare system
        run: |
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          date
          sudo apt update
          sudo apt install -y bc lm-sensors pciutils wsdd2 
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
          genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
          libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
          python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
          swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Prepare workspace
        run: |
          sudo mkdir -p /mnt
          sudo chown $USER:$USER /mnt

      - name: Clone source
        run: |
          git clone --depth=1 $REPO_URL $WORKDIR

      - name: Run first script (add packages)
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/lede/lede*.sh | sed -n '1p')
          chmod +x "$FILE"
          "$FILE"

      - name: Feeds update
        run: |
          cd $WORKDIR
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config
        run: |
          mv $GITHUB_WORKSPACE/lede/.config $WORKDIR/.config   

      - name: Run second script
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/lede/lede*.sh | sed -n '2p')
          chmod +x "$FILE"
          "$FILE"

      - name: download
        run: |
          cd $WORKDIR
          make download -j8

      - name: Prepare config
        run: |
          cd $WORKDIR
          make clean
          make defconfig 
          #chmod +x $GITHUB_WORKSPACE/check-packages-status.sh
          #bash $GITHUB_WORKSPACE/check-packages-status.sh
          #chmod +x $GITHUB_WORKSPACE/auto-fix-packages.sh
          #
          ##### Remove commentâ€‘restore function #####
          #bash $GITHUB_WORKSPACE/auto-fix-packages.sh
          #
          chmod +x $GITHUB_WORKSPACE/check-packages.sh
          bash $GITHUB_WORKSPACE/check-packages.sh

      - name: Compile
        run: |
          cd $WORKDIR
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR=$CCACHE_DIR
          ccache -M $CCACHE_MAXSIZE
          make -j$(nproc) || make -j1

      - name: Package firmware
        run: |
          cd $WORKDIR
          rm -rf bin/packages || true
          rm -rf bin/targets/*/*/packages || true
          # If directory structure changes in the future, use this to delete packages
          # find bin -type d -name packages -exec rm -rf {} + || true
          rm -rf output || true
          rm -f lede_firmware.zip || true
          find bin/targets -maxdepth 3 -type f ! -path "*/packages/*" -print | zip -j lede_firmware.zip -@

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lede_firmware
          path: ${{ env.WORKDIR }}/lede_firmware.zip

      - name: Prepare output directory
        run: |
          cd $WORKDIR
          mkdir -p output

          # Move firmware zip to output
          mv lede_firmware.zip output/

          # Move all firmware files 
          find bin/targets -maxdepth 3 -type f ! -path "*/packages/*" -exec mv {} output/ \;

          ls -lh output

      - name: Create tag
        run: |
          TAG=$(date +"lede-%Y%m%d-%H%M")
          git tag -f "$TAG"
          git push -f origin "$TAG"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV

      - name: Detect device platforms
        run: |
          cd $WORKDIR/output

          # Find the manifest file (only one exists)
          MANIFEST_FILE=$(ls openwrt-*-*-*.manifest 2>/dev/null | head -n 1)

          if [ -z "$MANIFEST_FILE" ]; then
            echo "PLATFORMS=No manifest file found." >> $GITHUB_ENV
          else
            PLATFORM_INFO=$(echo "$MANIFEST_FILE" | \
              sed -E 's/^openwrt-([^-]+)-([^-]+)-([^ ]+)\.manifest/Architecture: \1\nSubtarget: \2\nDevice: \3/')

            echo "PLATFORMS<<EOF" >> $GITHUB_ENV
            echo "$PLATFORM_INFO" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          #files: ${{ env.WORKDIR }}/output/*
          files: ${{ env.WORKDIR }}/output/*.zip
          body: |
            ## Device Platform Information
            ```
            ${{ env.PLATFORMS }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
