name: Build OpenWrt

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions: 
  contents: write

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_NAME: openwrt
  WORKDIR: /mnt/openwrt
  CCACHE_DIR: /mnt/ccache_openwrt
  CCACHE_MAXSIZE: 10G

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        run: |
          df -h
          chmod +x $GITHUB_WORKSPACE/scripts/cleanup.sh
          chmod +x $GITHUB_WORKSPACE/scripts/free-disk-space.sh
          #sudo bash $GITHUB_WORKSPACE/scripts/cleanup.sh
          #sudo bash $GITHUB_WORKSPACE/scripts/free-disk-space.sh       #Use with caution, as it may damage the environment.

      - name: Prepare system
        run: |
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          date 
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3 python3-pip rsync unzip zlib1g-dev file wget ccache

      - name: Prepare workspace
        run: |
          sudo mkdir -p /mnt
          sudo chown $USER:$USER /mnt

      - name: Clone source
        run: |
          git clone --depth=1 $REPO_URL $WORKDIR

      - name: Run first script
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/openwrt/openwrt*.sh | sed -n '1p')
          chmod +x "$FILE"
          "$FILE"

      - name: Feeds update
        run: |
          cd $WORKDIR
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config
        run: |
          mv $GITHUB_WORKSPACE/openwrt/.config $WORKDIR/.config

      - name: Run second script
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/openwrt/openwrt*.sh | sed -n '2p')
          chmod +x "$FILE"
          "$FILE"

      - name: download
        run: |
          cd $WORKDIR
          make download -j8

      - name: Prepare config
        run: |
          cd $WORKDIR
          make clean
          make defconfig
          chmod +x $GITHUB_WORKSPACE/check-packages-status.sh
          chmod +x $GITHUB_WORKSPACE/auto-fix-packages-openwrt.sh
          chmod +x $GITHUB_WORKSPACE/check-packages.sh
          #
          #bash $GITHUB_WORKSPACE/check-packages-status.sh
          # Remove commentâ€‘restore function 
          #bash $GITHUB_WORKSPACE/auto-fix-packages-openwrt.sh
          #
          bash $GITHUB_WORKSPACE/check-packages.sh

      - name: Compile
        run: |
          cd $WORKDIR
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR=$CCACHE_DIR
          ccache -M $CCACHE_MAXSIZE
          make -j$(nproc) || make -j1

      - name: Detect platform
        run: |
          cd $WORKDIR
          FILE=$(find bin/targets -name "*.manifest" | head -n 1)
          BASE=$(basename "$FILE")
          ARCH=$(echo "$BASE" | cut -d'-' -f2)
          SUB=$(echo "$BASE" | cut -d'-' -f3)
          DEV=$(echo "$BASE" | sed -E 's/^openwrt-[^-]+-[^-]+-(.+)\.manifest/\1/')
          DATE=$(date +"%Y%m%d-%H%M")
          ZIP="openwrt-${ARCH}-${SUB}-${DEV}-${DATE}.zip"
          TAG="openwrt-${ARCH}-${SUB}-${DATE}"
          echo "ZIP=$ZIP" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Package firmware
        run: |
          cd $WORKDIR
          mkdir -p output
          find bin/targets -type f \
            ! -path "*/packages/*" \
            ! -name "*buildinfo" \
            ! -name "profiles.json" \
            | zip -j "$ZIP" -@
          mv "$ZIP" output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP }}
          path: ${{ env.WORKDIR }}/output/${{ env.ZIP }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          #files: ${{ env.WORKDIR }}/output/*
          files: ${{ env.WORKDIR }}/output/${{ env.ZIP }}
          body: |
            ## Device Platform Information

            Architecture: ${{ env.ARCH }}
            Subtarget:    ${{ env.SUBTARGET }}
            Device:       ${{ env.DEVICE }}

            Build Tag:    ${{ env.TAG_NAME }}
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
